name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.4.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5dfceea2e157392c32c3e2bed08a0f254ce72cb66813634ad9960bf515729dd"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
