name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0390670f924c06ecf728c8406f6abbf2751166cc55c3cbae10e01865b44fb2f9"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
