name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ea2cd4bba1dd3669ec619ef1700e537206fd395b05a76a31739c290f50de13d"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
