name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.6.2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da788df42bcaa006cc8a317815444c290a4f569ad18a4c252a6f7262735f2e07"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
