name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30411eb5217099994694210feda59115750cdfd77efdc98bcd7c4cf29088b839"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
