name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.4.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27d3aaceaba1aedcad241b5b3f0c7e052d32105e97031510bcc26a2296338e88"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
