name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre5+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "866745b4eec885fde2c95f8bb645d9dd47ac375e416a6daf4672c4114eac7a9a"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
