name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre5+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c04d4301056551c3a5258b9ebe437aa9c31016c7b2450ec313cda0b0cf0a5c88"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
