name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.4.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab75d290faa0caab76c0f9748595ed96d1d3b47357f6030b0d42d731bb779a19"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
