name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.2.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d86f210e36a4eca1343030f6a92b498fbe0afd2bacff4254a75f387ce367588"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
