name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f58e4fd27f18e6e553054b748ccd2ee5893e5bf4b126be5743b129e1bb56e95"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
