name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a6d58fb6c68e90c3c074015ef5c12e9fc563ad62314e4b5752e50bf845da1e6"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
