name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6b0403e7674ad9c8cee40c0416008c9257235b31a347ccfe5734e167494a569"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
