name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bcfb7b2a01ee9a3e9c2f98e91f8c07905e5ab3acffe818f0ef3a6ac55415b7e5"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
