name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88bf60851dc20a8943e9f2d67f79883f396e0d36e50fe458d8afd4a84bded9ad"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
