name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4405334634a12bf5434190fb5999b262c3dbfb390caa8f7ee68e8b0d18372e7"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
