name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f159077f04fbacc26c3b3910151ef6251bac4c915c7e3cfc40bb0af919ef6e2"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
