name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84e39431452ac052ec74106667437ab1f343fbf87d03c35f17a6e612359499ce"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
