name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c37e33ec2c5abd183cd1b5d14c3fabcba11a3b80af81cf1b7cf87e266848a87"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
