name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.4.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ff137e4d351176da73de5064377c3988b97f77ac81075c116ba6f98be7498db"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
