name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre5+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d506aca88a4a574440cbe3264d49ac76d0771b33b12735cfb35ad54a7d2ed56"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
