name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.6.2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "893808fda5080133eafc44854fb8817c8109698eb5faa9580fd792d38228a8be"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
