name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20313a1083898c8edc5fbacb4a0fb6b376f3973326b52e6c9da9f996ea8f9bb8"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
