name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caf9844f6307f8eda611fe4dc5ca9b99a775d66cfec0ae713b20c59ff5cc1f21"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
