name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ff57698094d7b119af0f835654537d2a83f25abc3c878ba4ca5439169612523"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
