name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2d5cf61f16b0382a36f521fffb04b9b5d75ca368cc105701f558c294835dd19"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
