name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.2+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e96da1f1890d5aedd9083fe5a0ffb82a07d36f9127ec242b09387876c363d388"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
