name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5f3b8ca50bc80af093e36ae4e5d276f6fdbb49d1628cf30ef9a8b9eab6fae09"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
