name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.1.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04aff7cc40b72bf1fff0a5b86682edb350a446f931b41d1013eb4f8a242feff7"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
