name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre3+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8fa788ad380813e49365cb7d3606d02e521d92f39f14c038bd35072a31b60a1"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
