name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.5.0+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8004afe37abdd1f3f60359a1dbed3768336c62a687c7b271717d7362bab9eb97"

[versions]
fabric = "0.14.17"
minecraft = "1.19.2"
