name = "Go Pound Soul Sand"
author = "Go Pound Sand"
version = "1.0.0-pre1+1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6ce8e5bf675038ca68e6799abf672408745ccb1fda2ca27ea9a8f27be0bdfd"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"
